## NumPy

In [1]:
import numpy as np

In [6]:
mylist  = [1, 2, 3, 4, 5]

In [8]:
myarray = np.array(mylist)

In [9]:
weights = [75,76,77,78,79]


In [10]:
heights = [1.75, 1.76, 1.77, 1.78, 1.79]

In [11]:
weights/heights


TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [14]:
weights = np.array(weights)

In [15]:
weights = np.array(heights)

In [20]:
weights / heights


array([1., 1., 1., 1., 1.])

In [24]:
type(np.array( [1,"hello",True]))

numpy.ndarray

# Sum

In [26]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]


In [27]:
np.array(list1) + np.array(list2)  # element-wise addition

array([5, 7, 9])

In [28]:
np.array(list1)>5

array([False, False, False])

# Multiple dimensions

In [29]:
twoDarray = np.array([weights, weights])

In [30]:
twoDarray.shape

(2, 5)

In [33]:
twoDarray[0][0]  # first row, first column

np.float64(1.75)

# Creating Arrays

In [35]:
np.arange(10)  # 0 to 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.zeros((10,4))  # 0 to 9

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
random_heights = np.round(np.random.normal(1.75, 0.1, 1000),2)  # mean, std, number of samples

In [46]:
random_heights

array([1.68, 1.59, 1.76, 1.81, 1.75, 1.71, 1.88, 1.81, 1.76, 1.6 , 1.81,
       1.67, 1.66, 1.65, 1.74, 1.73, 1.46, 1.7 , 1.84, 1.94, 1.61, 1.71,
       1.74, 1.69, 1.81, 1.74, 1.75, 1.75, 1.69, 1.76, 1.66, 1.86, 1.65,
       1.72, 1.55, 1.72, 1.79, 1.85, 1.88, 1.9 , 1.71, 1.95, 1.75, 1.82,
       1.69, 1.81, 1.79, 1.74, 1.77, 1.84, 1.65, 1.71, 1.56, 1.53, 1.61,
       1.64, 1.81, 1.77, 1.61, 1.66, 1.68, 1.73, 1.66, 1.55, 1.83, 1.69,
       1.76, 1.73, 1.72, 1.86, 1.93, 1.79, 1.67, 1.71, 1.78, 1.77, 1.79,
       1.71, 1.85, 1.6 , 1.72, 1.82, 1.85, 1.93, 1.74, 1.68, 1.87, 1.84,
       1.83, 1.84, 1.81, 1.65, 1.82, 1.88, 1.53, 1.65, 1.67, 1.72, 1.87,
       1.88, 1.83, 1.73, 1.85, 1.75, 1.8 , 1.87, 1.74, 1.74, 1.54, 1.83,
       1.75, 1.75, 1.66, 1.81, 1.87, 1.66, 1.76, 1.65, 1.69, 1.64, 1.73,
       1.88, 1.89, 1.75, 1.66, 1.69, 1.61, 1.92, 1.74, 1.78, 1.66, 1.63,
       1.89, 1.78, 1.84, 1.62, 1.75, 1.84, 1.81, 1.74, 1.77, 1.8 , 1.8 ,
       1.9 , 1.66, 1.84, 1.7 , 1.65, 1.71, 1.64, 1.

In [47]:
random_heights.shape

(1000,)

In [48]:
random_weights = np.round(np.random.normal(75, 10, 1000),2)  # mean, std, number of samples

In [49]:
random_weights

array([ 77.55,  88.13,  58.73,  74.23,  64.9 ,  87.58,  83.87,  71.36,
        81.26,  65.58,  84.1 ,  68.71,  57.18,  68.81,  81.56,  72.1 ,
        71.47,  57.81,  92.28,  77.84,  80.94,  80.83,  70.78,  78.79,
        82.  ,  65.92,  72.03,  76.76,  78.19,  82.28,  67.2 ,  87.22,
        78.1 ,  72.67,  83.52,  78.7 ,  73.01,  70.37,  57.9 ,  72.64,
        60.45,  80.21,  86.24,  54.47,  77.43,  66.72,  71.68,  70.11,
        69.49,  78.07,  71.49,  59.41,  72.13,  79.13,  73.15,  55.45,
        67.69,  70.69,  73.69,  65.84,  69.87,  71.44,  88.8 ,  71.04,
        67.76,  72.52,  75.92,  73.33,  76.69,  79.34,  81.14,  69.14,
        68.57,  73.19,  82.47,  78.86,  71.64,  70.83,  77.23,  88.81,
        74.88,  85.87,  65.79,  68.94,  72.47,  68.77,  73.39,  73.78,
        56.21,  84.61,  50.24,  81.65,  60.84,  70.73,  76.33,  86.23,
        72.91,  74.32,  87.92,  56.15,  77.4 ,  87.18,  68.56,  67.98,
        77.64,  82.73,  81.75,  71.53,  73.34,  70.22,  76.04,  80.08,
      

In [50]:
np.column_stack((random_weights, random_heights))  # stack two arrays as columns

array([[77.55,  1.68],
       [88.13,  1.59],
       [58.73,  1.76],
       ...,
       [76.92,  1.73],
       [60.89,  1.72],
       [76.63,  1.73]], shape=(1000, 2))

In [51]:
data = np.column_stack((random_weights, random_heights))

In [52]:
data

array([[77.55,  1.68],
       [88.13,  1.59],
       [58.73,  1.76],
       ...,
       [76.92,  1.73],
       [60.89,  1.72],
       [76.63,  1.73]], shape=(1000, 2))

In [54]:
np.mean(data[:,1])

np.float64(1.75021)

In [57]:
np.min(data[:,1])


np.float64(1.46)

In [65]:
data[100, 1]  # first 10 rows, first column

np.float64(1.83)